/* ============================================================================
   SearchPalette
   ============================================================================
   Foundation, edit with care.

   A Cmd/Ctrl-K command palette over the site's own content, powered by
   Pagefind (astro-pagefind). Pagefind builds a static full-text index from the
   prerendered HTML at build time and ships it to /pagefind/; this island loads
   that index lazily on first open and queries it client-side. No backend.

   Behavior:
     - A magnifying-glass button in the header opens the palette.
     - Cmd-K (mac) / Ctrl-K (win) toggles it from anywhere.
     - Type to search; results update (debounced). Arrow keys move the
       selection, Enter navigates, Esc closes and returns focus to the button.

   Accessibility: role="dialog" + aria-modal, the input is labelled, the result
   list is a listbox, focus moves to the input on open and back to the trigger
   on close. Motion is minimal and the global reduced-motion rule neutralizes
   the fade.

   Security: Pagefind excerpts arrive as HTML with <mark> tags around hits. We
   do NOT inject them as raw HTML; renderExcerpt parses them with DOMParser and
   rebuilds plain text + <mark> as React nodes, so there is no innerHTML sink.

   Dev note: Pagefind only exists after a build, so in `astro dev` the index may
   be absent and a search shows the "no results" state. It works in preview and
   production where the index is generated.
   ============================================================================ */

import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { Search } from 'lucide-react';

interface PagefindResultData {
  url: string;
  excerpt: string;
  meta: { title?: string };
}
interface PagefindResult {
  id: string;
  data: () => Promise<PagefindResultData>;
}
interface Pagefind {
  search: (q: string) => Promise<{ results: PagefindResult[] }>;
}

interface Hit {
  url: string;
  title: string;
  excerpt: string;
}

/**
 * Turn a Pagefind excerpt ("...the <mark>quote</mark>-first flow...") into safe
 * React nodes. Parsing with DOMParser (no script execution) and rebuilding the
 * tree avoids dangerouslySetInnerHTML and decodes entities correctly.
 */
function renderExcerpt(html: string): ReactNode {
  if (typeof window === 'undefined' || typeof DOMParser === 'undefined') {
    return html.replace(/<[^>]+>/g, '');
  }
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const nodes: ReactNode[] = [];
  doc.body.childNodes.forEach((node, i) => {
    if (node.nodeType === Node.ELEMENT_NODE && (node as Element).tagName === 'MARK') {
      nodes.push(
        <mark key={i} className="bg-transparent font-semibold text-link">
          {node.textContent}
        </mark>,
      );
    } else {
      nodes.push(node.textContent);
    }
  });
  return nodes;
}

export default function SearchPalette() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [hits, setHits] = useState<Hit[]>([]);
  const [active, setActive] = useState(0);
  const [loading, setLoading] = useState(false);

  const pagefindRef = useRef<Pagefind | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);

  // Lazy-load the Pagefind bundle once, on first open. The path is absolute and
  // only exists in the built site, so it is hidden from Vite's resolver.
  const loadPagefind = useCallback(async (): Promise<Pagefind | null> => {
    if (pagefindRef.current) return pagefindRef.current;
    try {
      // Built from a runtime value so the bundler leaves it external (the file
      // is generated by Pagefind at build time and only exists in the output).
      const url = `${window.location.origin}/pagefind/pagefind.js`;
      const mod = (await import(/* @vite-ignore */ url)) as unknown as Pagefind;
      pagefindRef.current = mod;
      return mod;
    } catch {
      return null;
    }
  }, []);

  // Global shortcut: Cmd/Ctrl-K toggles the palette.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setOpen((v) => !v);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  // On open: focus the input and warm up the index. On close: reset + restore
  // focus to the trigger.
  useEffect(() => {
    if (open) {
      void loadPagefind();
      requestAnimationFrame(() => inputRef.current?.focus());
    } else {
      setQuery('');
      setHits([]);
      setActive(0);
      triggerRef.current?.focus();
    }
  }, [open, loadPagefind]);

  // Debounced search whenever the query changes while open.
  useEffect(() => {
    if (!open) return;
    const q = query.trim();
    if (!q) {
      setHits([]);
      setLoading(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    const t = setTimeout(async () => {
      const pf = await loadPagefind();
      if (!pf || cancelled) {
        if (!cancelled) setLoading(false);
        return;
      }
      const { results } = await pf.search(q);
      const top = await Promise.all(results.slice(0, 6).map((r) => r.data()));
      if (cancelled) return;
      setHits(
        top.map((d) => ({
          url: d.url,
          title: d.meta?.title ?? d.url,
          excerpt: d.excerpt,
        })),
      );
      setActive(0);
      setLoading(false);
    }, 130);
    return () => {
      cancelled = true;
      clearTimeout(t);
    };
  }, [query, open, loadPagefind]);

  // Keyboard nav inside the dialog.
  const onDialogKey = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') {
      e.preventDefault();
      setOpen(false);
    } else if (e.key === 'ArrowDown') {
      e.preventDefault();
      setActive((i) => Math.min(i + 1, Math.max(hits.length - 1, 0)));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActive((i) => Math.max(i - 1, 0));
    } else if (e.key === 'Enter' && hits[active]) {
      e.preventDefault();
      window.location.href = hits[active].url;
    }
  };

  return (
    <>
      <button
        ref={triggerRef}
        type="button"
        onClick={() => setOpen(true)}
        aria-label="Search the site"
        title="Search (Ctrl/Cmd K)"
        className="search-trigger inline-flex h-9 w-9 items-center justify-center rounded-md text-text transition-colors duration-150 hover:text-accent focus-visible:outline-2 focus-visible:outline-accent focus-visible:outline-offset-2"
      >
        <Search className="size-5" aria-hidden="true" />
      </button>

      {open && (
        <div
          className="fixed inset-0 z-[80] flex items-start justify-center bg-primary/60 p-4 pt-[12vh] backdrop-blur-sm"
          role="dialog"
          aria-modal="true"
          aria-label="Search the site"
          onKeyDown={onDialogKey}
          onClick={(e) => {
            if (e.target === e.currentTarget) setOpen(false);
          }}
        >
          <div className="w-full max-w-xl overflow-hidden rounded-xl border border-border bg-bg shadow-[var(--shadow-frame)]">
            <div className="flex items-center gap-s border-b border-border px-m py-s">
              <Search className="size-5 shrink-0 text-text-muted" aria-hidden="true" />
              <input
                ref={inputRef}
                type="search"
                value={query}
                onChange={(e) => setQuery(e.currentTarget.value)}
                placeholder="Search work, services, journal…"
                aria-label="Search query"
                aria-controls="search-results"
                className="w-full bg-transparent py-1 font-body text-base text-text outline-none placeholder:text-text-muted"
                autoComplete="off"
                spellCheck={false}
              />
              <kbd className="hidden shrink-0 rounded border border-border px-1.5 py-0.5 font-mono text-[0.7rem] text-text-muted sm:inline">
                Esc
              </kbd>
            </div>

            <ul
              id="search-results"
              role="listbox"
              aria-label="Search results"
              className="max-h-[55vh] overflow-y-auto"
            >
              {query.trim() && !loading && hits.length === 0 && (
                <li className="px-m py-l text-center text-sm text-text-muted">
                  No matches for “{query.trim()}”.
                </li>
              )}
              {!query.trim() && (
                <li className="px-m py-l text-center text-sm text-text-muted">
                  Search case studies, services, and journal entries.
                </li>
              )}
              {hits.map((hit, i) => (
                <li key={hit.url} role="option" aria-selected={i === active}>
                  <a
                    href={hit.url}
                    onMouseEnter={() => setActive(i)}
                    className={`block border-b border-border px-m py-s no-underline transition-colors duration-100 last:border-b-0 ${
                      i === active ? 'bg-bg-soft' : ''
                    }`}
                  >
                    <span className="block font-display text-lg text-heading">{hit.title}</span>
                    <span className="mt-0.5 block text-sm leading-[1.45] text-text-muted">
                      {renderExcerpt(hit.excerpt)}
                    </span>
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}
    </>
  );
}
